### ISSUE TITLE
Console runner throws MissingMethod exception

### ISSUE THREAD

**Issue by benfranklin79** [machine/machine.specifications.runner.console#8]
I'm trying to run tests in the following repo:

https://github.com/Yegoroff/PlainElastic.Net

I've used the nuget package manager console to install this console app (version 0.9.0) to a local package directory:

I have a batch file which runs as follows:

```
set MSPEC_DIRECTORY="C:\checkouts\PlainElastic.Net\packages\Machine.Specifications.Runner.Console.0.9.0\tools\mspec-clr4.exe"
set TESTLIB_PATH="C:\checkouts\PlainElastic.Net\src\PlainElastic.Net.Tests\bin\Debug\PlainElastic.Net.Tests.dll"

%MSPEC_DIRECTORY% %TESTLIB_PATH%
```
When I run it I get an exception:

```
Runner failure: System.MissingMethodException: Constructor on type 'Machine.Specifications.Runner.Impl.DefaultRunner' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at Machine.Specifications.Runner.Utility.AppDomainRunner.CreateRunnerInSeparateAppDomain(AppDomain appDomain, AssemblyPath assembly)
Constructor on type 'Machine.Specifications.Runner.Impl.DefaultRunner' not found.
```

In this solution version 0.6.2 of Machine.Specifications is being used which I suspect may be the problem but I don't know where to get hold of an older version of the console runner to try against it

**Comment by danielmarbach** [comment]
Yes that's the problem. 0.9 console required core 0.9 or higher

0.6.2 has the runner bundled with it. Meaning the nuget package has a tools folder

**Comment by benfranklin79** [comment]
Found the runner and it works great. Thanks!
